application:
  server-url: ${env.application.server-url:http://localhost:8081}


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
#  sleuth:
#    propagation-keys:
#      - DigitalAuthentication
  application:
    name: sleuth-client-test