server:
  port: 8082

queue:
  name: queueTest

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  sleuth:
#    propagation-keys:
#      - DigitalAuthentication
  application:
    name: sleuth-consumer-test
